### ISSUE TITLE
How to retrieve list of units in use

### ISSUE THREAD

**Issue by xhocquet** [Shopify/measured-rails#38]
Hey, I'm looking for an easy way to retrieve a list of units used by the library to use in a collection select. Something like:

```
collection_select(@grain_store, :store_weight_unit, Measured.UNITS .... )
```

I looked through the source and didn't see anything clearly public, would there be any interest in adding this?

**Comment by kmcphillips** [comment]
From the [README.md](https://github.com/Shopify/measured#usage):

See all valid units:

```ruby
Measured::Weight.unit_names
> ["g", "kg", "lb", "oz"]
```

See all valid units with their aliases:

```ruby
Measured::Weight.unit_names_with_aliases
> ["g", "gram", "grams", "kg", "kilogram", "kilograms", "lb", "lbs", "ounce", "ounces", "oz", "pound", "pounds"]
```

👍
