### ISSUE TITLE
Support 0 for numericality validations

### ISSUE THREAD

**Issue by kmcphillips** [Shopify/measured-rails#5]
Related to #4 @cyprusad 

Validations for numericality check for a `Measurable` subclass, but in the special case of 0 we should allow a number and coerce it. Having to say `0 cm` doesn't make sense.

This would currently error:

``` ruby
validates :length, measured: { greater_than: 0 }
```

**Comment by cyprusad** [comment]
C'est une bon ideé :sparkles:

**Comment by thegedge** [comment]
Given measured 2.0 will take a stricter stance on this (since, for example, `0°C != 0°F`), we won't be able to support comparison and arithmetic with scalars.
